version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
      PG_DATA: /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/
  todo-app:
    build: ./
    command: ./todo-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=postgres
volumes:
  db: